services:
  postgres:
    restart: always
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: ${DBNAME}
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASS}
    volumes:
      - ./data/db_data:/var/lib/postgresql/data
    ports:
      - "${DBPORT}:${DBPORT}"
