services:
  postgres:
    restart: always
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./data/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
